### ISSUE TITLE
Files look like items in folders

### ISSUE THREAD

**Issue by eddiemonge** [jesseweed/seti-ui#22]
Files should be lined up with the folder arrows so they don't look like the children in them. This can be done with:

``` css
.list-tree.has-collapsable-children .list-nested-item li.file {
  padding-left: 0;
}
```
