### ISSUE TITLE
Clarification on fonts

### ISSUE THREAD

**Issue by timdp** [jesseweed/seti-ui#240]
The 1.0 release caught me by surprise, especially the fonts. I'm sure I'll get used to them, but what's the intended font face? I had to go into DevTools to find out that the primary font family for `atom-workspace` is actually Roboto rather than a somewhat oddly padded Arial. Could you perhaps add that to the readme?

Also, the tree view is now pretty huge compared to the previous version. Maybe compact mode could influence that as well?

**Comment by bruinebeer** [comment]
Yeah, it looks way too different from the previous version imo.. feels like i'm using the material ui. It would be better if it was closer to the previous version considering the font-face & font styling.

I would also appreciate an option to disable the animations.

**Comment by jwerts** [comment]
Agree that everything's too big - even in compact mode.  I thought something had gone wrong when it updated this morning.

**Comment by bruinebeer** [comment]
This eases the pain a little bit.

```LESS
@font-size: .8rem;

html,
body,
.tree-view,
.tooltip,
.tab-bar .tab,
.find-and-replace .find-meta-container,
atom-text-editor[mini],
.btn,
.status-bar,
linter-message {
  font-size: @font-size;
}

.tree-view *,
.tooltip,
.tab-bar .tab * {
  font-weight: 500;
}
```
