### ISSUE TITLE
option to change editor background color / how to manually edit it ?

### ISSUE THREAD

**Issue by rebornishard** [jesseweed/seti-ui#246]
i love seti ui color combination, but not for text editor background color
sir how to override text editor background color
and it's possible to editing it ?
thanks

**Comment by bruinebeer** [comment]
just add this to your stylesheet

```Less
atom-text-editor {
  background-color: #101010; // or choose whatever
}
```
