### ISSUE TITLE
Weird text placement in Tab headers

### ISSUE THREAD

**Issue by simbuerg** [jesseweed/seti-ui#298]
Hey,

I'm on Atom 1.7.4 and got weird placement of tab headers with the current version of seti-ui. It looks like a newline sneaked itself in ;-).

Example:
![screenshot_small](https://cloud.githubusercontent.com/assets/598281/15707117/413293ba-27f7-11e6-899b-3d3dad27ce4d.png)

**Comment by glasnak** [comment]
I have a similar issue, working on CentOS 7 and Atom 1.7.2 and current version of seti ui.
Example:
![atom-bs](https://cloud.githubusercontent.com/assets/2435886/15709754/bc082654-2806-11e6-9618-dc1e1c7d04c6.png)

**Comment by rkichenama** [comment]
similar issue, Windows 10 and Atom 1.7.4

![image](https://cloud.githubusercontent.com/assets/1634457/15714519/d47d9d5e-27e8-11e6-8ecb-6784a27b3095.png)

**Comment by RhyCynn** [comment]
I'm not sure what the proper protocol is here for posting workarounds, but I had to override the following styles in my styles.less file:

```css
atom-workspace-axis.vertical .tab-bar .tab {
    padding: 17px 30px;
}

atom-workspace.seti-compact atom-workspace-axis.vertical .tab-bar .tab {
    padding: 7px 30px;
}

atom-workspace .tab-bar .tab .title::before {
    margin-top: -2px;
    margin-left: -25px;
}
```
