### ISSUE TITLE
Consider usability of active tab color and contrast between UI elements

### ISSUE THREAD

**Issue by xtravar** [jesseweed/seti-ui#313]
On many occasions, I've been "lost" in Atom's UI and unnecessarily clicked the active tab.  This is primarily for the following reasons:
- the darker active background color indicates "below", but if it is the active tab, it is conceptually "above"
- the tree view background color is very similar, and being next to the tabs makes it look like two tabs are active at the same time
- users are familiar with the darker = inactive concept from other applications
- the shades of grey simply do not have much differentiation
- the text color on all of the things along the tab bar is bright white, regardless of it's importance in the UI
- the color separator sits in between the tab and its content more than the other tabs, which is conceptually difficult to process

I don't know how much of this can be changed without ruining the aesthetic direction or making other problems. It seems like there might be Atom limitations too.

I made the following haphazard tweak to my styles.less, resulting in a more pronounced "this is the tab I am editing".

``` less
atom-workspace-axis.vertical .tab-bar {
  border-bottom: 1px solid #519aba;

  .tab {
    // inactive tabs lower opacity on icon/title
    .title, .close-icon {
      opacity: 0.3;
    }

    border-bottom: 0px;
    bottom: 1px;

    &::after {
      bottom: -1px;
    }

    &.active {
      .title, .close-icon {
        opacity: 1;
      }

      &::after {
        left: -1px;
        width: calc(100% + 1px);
        background-color: inherit;
      }
    }
  }
}
```

**Comment by ami** [comment]
i ran into the same usability concerns with the active tab coloring.

thanks for the code snippet @xtravar! added it in my stylesheet (but using a 2px border instead of 1px, purely for aesthetic reasons) and it's been helping a lot 😄

**Comment by xtravar** [comment]
Cool! Glad it helped someone else.  I made the following changes since then.

```less
atom-workspace-axis.vertical .tab-bar {
  background-color: darken(#519aba, 42%);
  border-bottom: 1px solid #519aba;

  .tab {
    // inactive tabs lower opacity on icon/title
    opacity: 0.8;
    .title, .close-icon {
      opacity: 0.6;
    }

    border-bottom: 0px;
    bottom: 1px;

    &::after {
      bottom: -1px;
    }

    &.active {
      opacity: 1;
      .title, .close-icon {
        opacity: 1;
      }

      &::after {
        left: -1px;
        width: calc(100% + 1px);
        background-color: inherit;
      }
    }
  }
}

atom-panel-container.left {
  background-color: darken(#519aba, 42%);
}

.tree-view {
  .directory.project-root {
    >.header {
      background-color: inherit;
      .name {
        color: #519aba;
      }
    }
  }

  .entries {
    .directory.entry>.header {
      color: darken(#519aba, 5%);
    }

    .file.entry .name {
      color: darken(white, 50%);
    }
  }
}

atom-text-editor atom-text-editor-minimap,
atom-text-editor::shadow atom-text-editor-minimap {
  background: darken(#519aba, 42%);
}

atom-text-editor atom-text-editor-minimap::shadow .minimap-visible-area::after,
atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-visible-area::after {
  background-color: rgba(255, 255, 255, 0.1);
}


atom-text-editor,
atom-text-editor::shadow {
  .find-result .region {
    border: none;
  }
}

atom-text-editor::shadow .highlight.find-result .region {
  background: darken(#519aba, 39%);
  z-index: -100000;
}
```
