### ISSUE TITLE
background-box "Open Config Folder" not wide enough on more panes

### ISSUE THREAD

**Issue by C-Bouthoorn** [jesseweed/seti-ui#332]
When using 2 panes, the width of the box at the background of "Open Config Folder" in the Settings menu isn't wide enough to fit the text.

![screenshot from 2016-09-10 13-18-04](https://cloud.githubusercontent.com/assets/10348289/18410122/647cf836-7759-11e6-8514-1cd863b9ad5a.png)

In case my `styles.less` could interfere with this:

``` less
@background: '~/Pictures/Backgrounds/Flat Mountains Landscape.jpg';
@font-family: 'Fira Mono';
@font-size: 12px;

atom-workspace {
  //* Set background
  background: url(@background);
  background-size: cover;

  font-family: @font-family;
  font-size: @font-size !important;

  status-bar {
    font-size: @font-size;
  }

  autocomplete-suggestion-list, .suggestion-description-more-link, .suggestion-description-content {
    font-family: @font-family !important;
  }

  //* Remove the default background from the tree-view and tab's title
  .tree-view, .title {
    background: none !important;
    font-size: @font-size;
  }

  //* Bit of space between the tabs
  .tab {
    margin-right: 1px !important;
  }

  //* Font of the directory list
  atom-panel-container {
    .left {
      font-family: @font-family;
      font-size: @font-size;
    }

    .list-tree.has-collapsable-children li.list-item {
      margin-left: 0;
    }
  }


  //* Background of line numbers
  .gutter-container, .line-numbers, .gutter {
    background: none !important;
    background-color: #fff !important;
    font-size: @font-size;
  }

  //* Make filetree see-through
  .left, .selected::before {
    background: rgba(0, 0, 0, 0.5) !important;
  }

  //* Make code background a bit darker, so you can read the code
  atom-text-editor, .tool-panel, .tab-bar, .tab, atom-pane {
    background: rgba(0, 0, 0, 0.5) !important;
    font-family: @font-family;
    font-size: @font-size;
  }

  //* Remove ugly bar above tabs
  atom-pane {
    padding: 0 !important;
    font-size: @font-size;
  }
}
```
