### ISSUE TITLE
Command Palette not wide/padded enough for output

### ISSUE THREAD

**Issue by dhollinger** [jesseweed/seti-ui#383]
Command Palette is too small for some plugins' output and instead ends up overlaying output on top of each other.

Example from the git-plus plugin with Seti-UI:
![seti-screen](https://cloud.githubusercontent.com/assets/2914211/22339784/c6a79868-e3b0-11e6-9b2e-e5ddc8d9afa5.png)

Same example with the Atom Dark UI:
![atom-screen](https://cloud.githubusercontent.com/assets/2914211/22339912/40d57420-e3b1-11e6-9d2c-f7cd5f7f8cb2.png)

Same example with the Material UI:
![mat-screen](https://cloud.githubusercontent.com/assets/2914211/22339924/4c33682c-e3b1-11e6-84e6-60b18cfa6156.png)

**Comment by forestgagnon** [comment]
FYI as a workaround you can specify a custom modal width for things like command pallette in your `styles.less`. I use this snippet to make modals wider:
```less
atom-workspace, atom-text-editor {
  .modal {
    width: 800px;
    margin-left: -400px;
  }
}
```
