### ISSUE TITLE
Setting the background color of the tree-view panel when it has focus

### ISSUE THREAD

**Issue by terrycloth** [jesseweed/seti-ui#463]
I think it would be nice if the Tree View panel were a little lighter or darker, depending on whether it currently has focus. This way it's easier to see if the focus is currently in one of the editor tabs or panes or the Tree View, so you don't accidentally send the wrong commands to the wrong pane.

I tried setting the background color myself from my user stylesheet, but I think Seti has done the Tree View styles in particular in such a way that it's very hard to override them, even with absurdly specific CSS selectors like this:

``` css
html body atom-workspace atom-panel-container.left atom-dock.left atom-pane-container.panes atom-pane.pane .item-views .tool-panel.treeview {
    background-color: black !important;
}
```

I would personally be satisfied with help figuring out the selector I would need to change the Tree View background color in my own stylesheet, but I thought other users might also appreciate this. So you could consider this either a support or feature request.

Thanks.
