### ISSUE TITLE
text overflow in tooltips

### ISSUE THREAD

**Issue by RumpelRaisch** [jesseweed/seti-ui#510]
On files with long paths the tooltip looks strange with overflowing text:
![20181012-142824-rainer schulz](https://user-images.githubusercontent.com/6524137/46869159-2a190b00-ce2b-11e8-86ef-409faa0596f4.png)
Best regards.

**Comment by RumpelRaisch** [comment]
I added this to my `styles.less` to fix it:
```less
    .tooltip {
        .tooltip-inner {
            max-width: none;
        }
    }
```
