### ISSUE TITLE
non-ideal settings page with the update from atom 0.168.0

### ISSUE THREAD

**Issue by AndalfTheBeard** [jesseweed/seti-ui#76]
![example image](http://i.imgur.com/K3A2ihO.png)
![example image 2](http://i.imgur.com/FLUxa67.png)

Pretty sure this will be getting a fix soon, but I thought I'd bring it up anyway. It's really hard to read disabled options in selection boxes on the settings page with this theme and there's also something irregular about the green edge to those buttons.

**Comment by simurai** [comment]
There is a PR #72 waiting that should fix this.

In the meantime you could add this to "Menu > Open Your Stylesheet":

```css
.settings-view {
  .btn {
    color: #fff;
  }
  select.form-control {
    border: none;
    color: #fff;
  }
}
```
